### ISSUE TITLE
is it too late for a suffix version?

### ISSUE THREAD

**Issue by dominictarr** [multiformats/multihash#1]
some things sort by prefixes (i.e. leveldb), and you would maybe rather keep the hashes uniformly distributed (at least you can reason about it).

For example, this would play much nicer with leveldb if it was a suffix not a prefix.

**Comment by mafintosh** [comment]
just curious, whats the use-case for storing the length of the hash?

**Comment by jbenet** [comment]
truncated hashes. some people, for example, use a sha2-512 truncated to 256 bits instead of sha256 because in some archs it's faster.
