### ISSUE TITLE
Are codes for Blake2b and Blake2s across implementations incosistent?

### ISSUE THREAD

**Issue by arnau** [multiformats/multihash#100]
Hello, I'm not sure I'm missing something important here but in the list of implementations some use {Blake2b 0x40, Blake2s 0x41} and others {Blake2b 0xb240, Blake2s 0xb260}. The latter agreeing with multibase and multihash CSV tables.

Are both valid? Are the former old/obsolete?

**Comment by Stebalien** [comment]
No, the first ones look incorrect. Which implementation uses 0x40 and 0x41?

**Comment by Stebalien** [comment]
Ah, interesting, it looks like it was changed a few years ago.

**Comment by Stebalien** [comment]
It looks like this was changed to take into account the fact that these hash functions are parameterized over their length. 0xb240 is actually blake2b-512 while 0x40 didn't actually *specify* the length.

**Comment by Stebalien** [comment]
One here: https://github.com/multiformats/clj-multihash/issues/11

**Comment by arnau** [comment]
True, worth mentioning that the ongoing PR #41 still has a mention to the 0x40 and 0x41.

**Comment by ebkalderon** [comment]
The descriptions of the BLAKE2 hash codes on [Multiformats.io](https://multiformats.io/multihash/#blake2b-512-512-bits) and in the [IETF draft spec for multihashes](https://tools.ietf.org/html/draft-multiformats-multihash-00#appendix-B.5) suggest that the correct codes for BLAKE2 are:

Algorithm | Code
----|----
Blake2b-512 | `0xb240`
Blake2b-256 | `0xb220`
Blake2s-256 | `0xb260`
Blake2s-128 | `0xb250`

**Comment by arnau** [comment]
Looks like this issue has been solved. Perhaps it would be good to mention in the list of implementations the ones that are not up to date?

Thanks for the help 👍

**Comment by Stebalien** [comment]
I've been filing bugs but probably haven't found all of them.
