### ISSUE TITLE
which codecs from multicodec table.csv are defined and should be implemented in multihash

### ISSUE THREAD

**Issue by fluency03** [multiformats/multihash#105]
As it is stated here:

> *We use a single multicodec table across all of our multiformat projects. The shared namespace reduces the chances of accidentally interpreting a code in the wrong context.*

However, there are too many codec in the table. It is not clear:

**Which codecs from [multicodec table.csv](https://github.com/multiformats/multicodec/blob/master/table.csv) are defined and should be implemented as multihash?**

For example, maybe the BaseN (`base8`, `base16`, `base32`, ...) are not hashes and, the SHAs and blake2b definitely are hashes. `http`, `udp`, `ip4` are not hashes as well.

So, from this table https://github.com/multiformats/multicodec/blob/master/table.csv, we still need clearity that which are treated as hashes and should be implemented in the multihash project.

**Comment by raulk** [comment]
The code table is divided in sections each of which has a header line with no code value, specifying if the block that follows are hashes, bases, multiaddr protocols, etc. If this is not enough, could you suggest an alternative?

**Comment by fluency03** [comment]
ok I understand. all codecs under `multihashes` are for hashes. thanks
