### ISSUE TITLE
What is an AppCode?

### ISSUE THREAD

**Issue by Stebalien** [multiformats/multihash#111]
go-multihash has a concept of "App Codes", anything in the range 0x0 - 0x10. What is this and should we remove it?

**Comment by daviddias** [comment]
Good question. @whyrusleeping ?

**Comment by whyrusleeping** [comment]
I have no idea.

**Comment by daviddias** [comment]
Thanks @whyrusleeping. @Stebalien I guess that gives you the answer you wanted :)
