### ISSUE TITLE
Why so many size-specific hash codes?

### ISSUE THREAD

**Issue by singpolyma** [multiformats/multihash#115]
There seem to be unique codes defined for a lot of algorithm-plus-size combinations, especially for blake2 and skein... why is this not handled using the length specifier?

**Comment by Stebalien** [comment]
Unfortunately, the length specifier is only used for truncation as that's a function common to all hash functions (well, except the identity "hash" function).

However, I'm not sure why we didn't just allow the hash function itself to handle the length (e.g., sha* would truncate, etc.). @daviddias, were you part of this discussion.

**Comment by Stebalien** [comment]
Unfortunately, _fixing_ this at this point may not be an option.

**Comment by filiphanes** [comment]
blake2b-256 truncated to 160bits gives different hash then blake2b-160 not truncated, so they are different hash functions
you can try it for example in python
```py
import hashlib

# blake2b-160 full
>>> hashlib.blake2b(b'hello', digest_size=20).digest().hex()
'b5531c7037f06c9f2947132a6a77202c308e8939'

# blake2b-256 truncated to 20bytes = 160bits
>>> hashlib.blake2b(b'hello', digest_size=32).digest()[:20].hex()
'324dcf027dd4a30a932c441f365a25e86b173def'

# blake2b-256 full
>>> hashlib.blake2b(b'hello', digest_size=32).digest().hex()
'324dcf027dd4a30a932c441f365a25e86b173defa4b8e58948253471b81b72cf'
