### ISSUE TITLE
What are the benefits of using multi-hash?

### ISSUE THREAD

**Issue by satoshi999** [multiformats/multihash#122]
What are the benefits of using multi-hash?

For example, even if you know the hash function, it will not be useful for decoding.
This is because sha256 is one-way hash and it is difficlut to restore.
And I think that it is a feature of the hash function.

If you will know the hash function from hash value, in what cases is it useful?

**Comment by raulk** [comment]
This is a general question about hashing; have a look at this section of the wikipedia article on usages of hash functions: https://en.wikipedia.org/wiki/Hash_function#Uses.

When you have a content + the digest of that content, it's useful to know _how_ (i.e. with which hash function) the digest was generated.
