### ISSUE TITLE
Inconsistent hash code bytes

### ISSUE THREAD

**Issue by austinabell** [multiformats/multihash#126]
Not sure where I should open this issue, but on https://multiformats.io/multihash/ it shows the prefix bytes for blake2 as encoded as bytes (for example blake2b-256 code in hex is b220) where in this repo it shows as being encoded as a uvarint (again blake2b-256 in hex as a0e402). It seems clear now that it should be encoded as uvarint so just opening issue to update on the multihash website and possibly update test vectors to include blake2 here?

The inconsistency is only for blake2 codes right now since it is above the threshold of uvarint being encoded as 3 bytes.

Also, I could not find any test cases for blake2 (why were those never updated when blake2 support was added?) or am I missing something or is there a more updated location for this?

**Comment by vmx** [comment]
Thanks a lot @austinabell for reporting, this is the right place. There is even already a bug report for almost 3 years open for the website: https://github.com/multiformats/website/issues/23 I'll make sure it gets updated soon.

I've opened https://github.com/multiformats/multihash/issues/127 for tracking the problem of missing text vectors.

**Comment by vmx** [comment]
I'm closing this issue as we now have a tracking issue for additional test cases (#127) and a PR on the website to fix the Blake2 examples (https://github.com/multiformats/website/pull/61). Please follow those in case you are interested.
