### ISSUE TITLE
Add the "Identity" hash function

### ISSUE THREAD

**Issue by jbenet** [multiformats/multihash#13]
sometimes the values to hash are smaller than a cryptographic hash digest, and merits just actually storing the data itself as the hash value. (Example use case: a multihash of an ed25519 256bit pub key [0]). 

Implementation:
- add a code for the "identity" hash function. (Could use `0x10` and don't add sha0, or `0x50`) 

Pros:
- can store ECC pub keys easier and use them in projects that use multihashes as IDs (IPFS)
- can store values smaller than the hash ("a type")

Cons:
- this worsens the "keep things uniform" expectation people have from hashes

[0]: 

> "On the other hand, elliptic-curve points are typically sent as 256 bits, and then a 256-bit hash doesn't save any space. Sending R instead of H(R,M) also has the advantage of allowing batch signature verification, which is typically twice as fast as verifying one signature at a time. That's why Ed25519 doesn't use this compression." -- from http://blog.cr.yp.to/20140323-ecdsa.html

**Comment by jbenet** [comment]
@robcat had the same idea and reminded me of this today-- we should add this.

**Comment by jbenet** [comment]
particularly useful:

>  <robcat> for example, in the semantic web (addressing a concept by keyword, no lookup required)

**Comment by whyrusleeping** [comment]
Some example usecases here would be nice to see.

**Comment by robcat** [comment]
@whyrusleeping A typical example would be the representation of [JSON-LD](http://json-ld.org/) objects. Most of the values will probably be shorter than 256 B.

**Comment by jbenet** [comment]
- Let's say that `0x00` is the Identity Hash Function's code in the standard table. 
- Let's say that the Identity Hash Function is: `(x) -> x`

```go
// example in Go
func IdentityHash(x []byte) []byte { return x }

// multihash(0x00, "foo") => 0x0003666f6f => ("identity", 3, "foo")
```

Added in #40

I will give a week before declaring this part of the spec.

**Comment by robcat** [comment]
@jbenet 
I would like the spec to address the following two points:
- Maximum length of the data: are implementations supposed to handle unbounded variable-size data?
- Encoding of the data: in your example the value `0x0003666f6f` gets automatically decoded as a string, does that imply that UTF-8 is the default encoding of the data?

**Comment by jbenet** [comment]
@robcat 
- a maximum would be useful. not sure what to choose though that wont be obsoleted. This could be an implementation parameter? not sure, it's bad from a security perspective not to leave this well-defined.
- sorry, my example didn't mean to decode/encode utf8. i meant it as just byte buffers.

**Comment by kumavis** [comment]
> Maximum length of the data
maybe data is length prefixed and then clients set sane max ~1 Mbyte

`[varint length-of-data][data]`

**Comment by kumavis** [comment]
I came up with a few use cases while writing the various Ethereum ipld format resolvers.
The Ethereum StateTrie leaf nodes each contain a binary blob for an Ethereum Account.
In order to provide all paths off of a StateTrie node, currently the ipld format resolver needs to include the logic for Ethereum Accounts to provide the paths off of the trieNode and off the Account.
The resolver implementations would be much simpler if they were able to say "here is path to an account, and here is its data, use the account resolver to resolve that account" which it could do by providing a cid that indicated the type (`eth-account`) and the data inline via the identity-hash.

**Comment by kumavis** [comment]
This is basically the `data:` uri of our time
https://tools.ietf.org/html/rfc2397

**Comment by Kubuxu** [comment]
It was implemented and uses literal `0` as code ID.

**Comment by kumavis** [comment]
ok great here is a PR to add it to the multicodec table https://github.com/multiformats/multicodec/pull/30

@Kubuxu is there a codec name you are using in the go impl?

**Comment by Kubuxu** [comment]
Sorry, I messed up, we added Identity multibase encoding, I don't know how about the multihash and so on.

**Comment by kumavis** [comment]
@Kubuxu ok removed the PR. What is the "Identity multibase encoding" ?

**Comment by Kubuxu** [comment]
It is just binary pass through for cases when rest of the stream/data is binary and encoding isn't needed.


As multihash was merged with multicodec I don't think there is need for Identity encoding anymore, it would be saying "here is some data, but now you have no idea what it is". We should reevaluate the usecases.

**Comment by Stebalien** [comment]
(long since fixed)
