### ISSUE TITLE
blake2b-256 annotated function code example, please chk

### ISSUE THREAD

**Issue by anupamblockchain** [multiformats/multihash#134]
at https://github.com/multiformats/multihash#idea-self-describe-the-values-to-distinguish , this example figure annotation for blake2b-256 shows a0e402 but as per multicodex table it is 0xb220 . M I interpreting wrong?

**Comment by vmx** [comment]
The reason is that the multicodec table lists the actual value, which is 0xb220. Those slides shows the encoded multihash, which means that the value was encoded as varint. The varint representation of 0xb220 is 0xa0e402.
