### ISSUE TITLE
XXHash support

### ISSUE THREAD

**Issue by delaneyj** [multiformats/multihash#149]
It's non-cryptographic but want to use CIDs in a game development context. Where speed is more important than cryptographic security. It dwarfs Blake in terms of performance and useful in situations where you control the data and aren't worried about bad actors.  There are implementations readily available in almost every language and most are built in assembly, even a wasm version is readily available.

**Comment by rvagg** [comment]
So there's at least two things you can do to make this happen, and I'm making an assumption that you're looking at this from JS from your other GitHub comments: add an entry to the [multicodec table
](https://github.com/multiformats/multicodec/blob/master/table.csv) if it doesn't already exist for this hasher (find a spot near similar hash functions that's later than `0x7f` somewhere), then provide an implementation for it. The model for this could be https://github.com/multiformats/js-murmur3 (which is also non cryptographic). There's also [sha3](https://github.com/multiformats/js-sha3) and the [blake2 set](https://github.com/multiformats/js-blake2). There's no reason it needs to be in the multiformats org but you can add a link to it at the bottom of the js-multiformats README.
For Go, a similar thing can happen, there's now a [go-multicodec](https://github.com/multiformats/go-multicodec) which has a registry that new things can be registered in, there's currently no spot on the README for implementations but one could/should be added when we have additional hashers that are compatible.
