### ISSUE TITLE
Inclusion of Set or MSet Hash Functions

### ISSUE THREAD

**Issue by OrionReed** [multiformats/multihash#150]
Set and Multiset hash functions fill important niches that are not currently supported by the hash functions in the table, such as content-addressing of unordered data without expensive sorting. 

While there are several hash functions in this category, I want to propose the inclusion of the [Elliptic Curve Multiset Hash](https://arxiv.org/abs/1601.06502#) (ECMH) which is an efficient homomorphic hash function with strong performance and security properties.

While ECMH is a strong candidate, the emphasis of my proposal is that there should be hash functions in this category, exactly which functions those are is up for debate.

**Comment by rvagg** [comment]
if you have a use for it and it's not currently included, feel free to open a PR @ https://github.com/multiformats/multicodec and we can have discussions about the specifics if the _fit_ is weird. Perhaps they won't make sense for use in a CID, but being able to uniquely identify a hash function is a generally useful property--as long as we don't run into problems like parameterised hash functions where the exact form of a hash function can't be identified just by the entry.
