### ISSUE TITLE
Murmur3 labelled as multihash

### ISSUE THREAD

**Issue by IS4Code** [multiformats/multihash#157]
Commenting on the distinction between `multihash` and `hash` in the table, shouldn't `murmur3-32` be also labelled as `hash` only? [As far as I can tell](https://en.wikipedia.org/wiki/MurmurHash), it is a non-cryptographic function, but it has been in the table as `multihash`, for a long while (#79).
@rvagg @vmx

**Comment by rvagg** [comment]
yes, it should be changed, would you mind submitting a PR to the multicodec table to change it?

**Comment by IS4Code** [comment]
> yes, it should be changed, would you mind submitting a PR to the multicodec table to change it?

@rvagg Sure, I'll also try to check if there aren't more multihashes like that. How about "identity", that also seems like a good candidate for `hash`, since it's not a one-way function.

**Comment by vmx** [comment]
I'd also put "identity" into the `hash` category.
