### ISSUE TITLE
Specification of format and behaviours

### ISSUE THREAD

**Issue by moreati** [multiformats/multihash#17]
Thinking about #16 I began writing a spec to document multihash in more detail.

The WIP is in https://github.com/moreati/multihash/tree/spec

**Comment by jbenet** [comment]
I'm doing a more serious spec in #41 -- contribute there if desired. Would be good to have proper ABNF

**Comment by pawal** [comment]
Is #41 the most recent text on this spec? I could perhaps spend some time on fixing it, but it would be great to have it as something other than a PR to work with.
