### ISSUE TITLE
Two questions: Size is de facto in first byte sometimes? Formal standard? 

### ISSUE THREAD

**Issue by ttmc** [multiformats/multihash#23]
At ascribe, we'd like to make [BigchainDB](https://github.com/bigchaindb/bigchaindb) interoperate with IPFS. One step will be identifying BigchainDB transactions by their multihash. (Currently we _assume_ all hashes are sha3-256, but that's easy enough to change, and it would be nice to allow for future hash functions.)

We currently have two questions about multihash:

1. The first byte identifies the hash function, so for example 0x16 means sha3-256. The second byte is the digest size in bytes, but wait, isn't that already encoded in the first byte (at least in this case)? Is the second byte as digest size just there for hash functions where the output size must be specified independently (as with SHAKE128)?
2. Is multihash going to be proposed as a formal standard with some standards body (such as an RFC)?

We created a related issue on the BigchainDB repository: https://github.com/bigchaindb/bigchaindb/issues/100

**Comment by Nemo157** [comment]
There's an answer for 1 at https://github.com/jbenet/multihash/issues/1#issuecomment-91783612

**Comment by jbenet** [comment]
@ttmc

1. as @Nemo157 said, it's not enough to base on the standard hash output. many people truncate or extend hashes.
2. yes it is. it's likely going to IETF. we're working on more formal specs now.

**Comment by jbenet** [comment]
Started larger spec in #41 -- follow along there.
