### ISSUE TITLE
Non-cryptographic hashes

### ISSUE THREAD

**Issue by jbenet** [multiformats/multihash#30]
What do we do about non-cryptographic hashes, such as [these](https://github.com/rurban/smhasher#smhasher)? Do we include them in the same table?

I'm leaning towards yes.

**Comment by jbenet** [comment]
I'm leaning towards yes because:
- we already plan on including "the identity hash function", which is not cryptographically safe.
- it is better than creating another table for a different but equivalent standard.

**Comment by RichardLitt** [comment]
> It is better than creating another table for a different but equivalent standard.

I agree with this.

**Comment by jbenet** [comment]
So far, it looks like we will start adding non cryptographic hashes. The well-known hash functions are not more than 16000, and thus 2 bytes are plenty. This is a small price to pay for not having two standards or two different standard tables.

**Comment by jbenet** [comment]
I'll give a week for people to voice reasonable discontent.

**Comment by jbenet** [comment]
Okay, we'll do this
