### ISSUE TITLE
Base32 encoding issues

### ISSUE THREAD

**Issue by mseri** [multiformats/multihash#31]
The base32 implementations that you are using does not seem to be the same as https://tools.ietf.org/rfc/rfc4648.txt

Can you give us more informations on the base32 specification that you are following? I would like to add it to https://github.com/mseri/crypto-multihash

**Comment by jbenet** [comment]
@mseri maybe look at github.com/jbenet/go-multihash to check?

**Comment by mseri** [comment]
That does not support base 32 as far as I can see, only 'raw', 'b16', 'b58' and 'b64'

**Comment by jbenet** [comment]
@mseri then what base32 specification are you talking about? the ones in https://github.com/multiformats/multihash#example ?  i think i used python tools. the example may be wrong?

**Comment by jbenet** [comment]
@mseri did you figure this out? i'll close this. please reopen if needed.

**Comment by mseri** [comment]
Sorry for the massive delay, the specification I was mentioning is the one in the RFC: https://tools.ietf.org/rfc/rfc4648.txt

If you used python's `base64` library then there must be something wrong in the example: the alphabet used by python (`base64._b32alphabet`) is `b'ABCDEFGHIJKLMNOPQRSTUVWXYZ234567'` and, even assuming to lowercase the alphabet, both base32 provided example contain the characters `0189` in the encoding. 

That was also one fo the discrepancies in my [haskell library](https://github.com/mseri/crypto-multihash): the RFC compliant base32 encoding was resulting in hashes looking quite different.

**Comment by jbenet** [comment]
Don't doubt it. Feel free to correct it. :)

**Comment by harlantwood** [comment]
Do we have a test suite that all multihash implementations could be run against, eg in sharness?

**Comment by mseri** [comment]
There are but they only test few hashes and only hex for the moment.
I can generate some codes using my haskell library if needed, or wait until we have a complete test suite. 

What content did you use to generate the hashes in the example?

**Comment by jbenet** [comment]
@mseri i don't recall. just change them all to be the same of something, maybe of `multihash`
