### ISSUE TITLE
add md5 hash?

### ISSUE THREAD

**Issue by dcbishop** [multiformats/multihash#34]
Might be not be considered secure now, but there's still plenty of legacy stuff out there using it that might need to be represented. In another issue was talk of adding non-cryptographic hashes.

**Comment by jbenet** [comment]
yeah makes sense.

**Comment by jbenet** [comment]
@dcbishop do you want to add md5 to the table? maybe other relevant hashes while we're at it.

**Comment by celeduc** [comment]
Closed with https://github.com/multiformats/multihash/pull/76
