### ISSUE TITLE
Moving this repo to https://github.com/multiformats/

### ISSUE THREAD

**Issue by chriscool** [multiformats/multihash#37]
This repo should probably be moved to: https://github.com/multiformats/

And maybe it should be merged into https://github.com/multiformats/specs

**Comment by RichardLitt** [comment]
This will happen. :)

**Comment by jbenet** [comment]
> This repo should probably be moved to: https://github.com/multiformats/

Done! Thanks 😄 

> And maybe it should be merged into https://github.com/multiformats/specs

👎  on this. i think we should keep an independent repo per format, because there's a lot of issues and important readme stuff for each of them. That repo may be used for meta coordination on writing IETF specs, etc.

**Comment by jbenet** [comment]
![](https://gateway.ipfs.io/ipfs/QmaL9mvdAfTy6MpG9EMNj27FGY7JxAp4mhae6AArmpRwU3/cap.png)

**Comment by chriscool** [comment]
Great, thanks!
