### ISSUE TITLE
varint limitations of multihash

### ISSUE THREAD

**Issue by Kubuxu** [multiformats/multihash#38]
As multihash plans to introduce varints can we agree on some limitations that would allow many implementations to be much simpler (I am looking here at for example C).

My proposal for future:
Use MSB Varint (1 on most significant bit means that there is still data) with limitation of 4 bytes, and MSB of 4th byte unused (and 1 there is invalid). This means that whole varint can be fitted into 31 bits which is nice feature for low level languages. 

This gives us: `127^4 == 260,144,641` possible hashing functions and `260144641/2^20 = 248MiB` maximum hash length.

*cc* @jbenet

**Comment by jbenet** [comment]
> Use MSB Varint (1 on most significant bit means that there is still data)

Let's decide on varints for all multiformats at once: https://github.com/multiformats/unsigned-varint i've put the proposal here: https://github.com/multiformats/unsigned-varint/issues/1

> with limitation of 4 bytes, and MSB of 4th byte unused (and 1 there is invalid).

- This assumption MUST NOT be in the spec. 
- It does make sense not to open up the door for huge numbers (>4 bytes), but this is an implementation detail. I think the spec should have an "implementation note" that recommends implementations to establish a max suitable for their own purposes.
- You could have the 4 byte max as you describe. Adjust it later if necessary. (read: most likely never)
- Deploying code is much easier than changing protocols. And you have to change client  code anyway to add functions to the table.
- And honestly, i wouldn't even implement varints until AFTER the table gets past 80 functions.

> This gives us: `127^4 == 260,144,641` possible hashing functions and

This spec MUST NOT make assumptions. What seems ridiculous now has a tendency of becoming true. We cannot know what lies in the future.

>  `260144641/2^20 = 248MiB` maximum hash length.

Multihash MUST NOT have a maximum hash length.

**Comment by Kubuxu** [comment]
Ok, understood. As I am writing in C again I am starting to think in therms of max handled things.

Let's leave the limitations to the implementation.

**Comment by jbenet** [comment]
I think this has been addressed.
