### ISSUE TITLE
C# implementation

### ISSUE THREAD

**Issue by tabrath** [multiformats/multihash#57]
I've created a new implementation in C# [here](https://github.com/tabrath/cs-multihash). Supports all suggested hash algorithms.

**Comment by RichardLitt** [comment]
@tabrath This is awesome! Would you be interested in moving this to the multiformats organization? You'd still be in charge of the repository.

**Comment by tabrath** [comment]
Sure, that would be nice!

**Comment by RichardLitt** [comment]
Alright! Added you to multiformats. Following this guide: https://github.com/ipfs/community/blob/master/organizations.md

Move your repo to this organization, and then ping me here and I'll re-add you as the owner.

**Comment by tabrath** [comment]
Ok, I've transferred the repo, should I continue the guide and change the README to the standarized format you're using?

**Comment by RichardLitt** [comment]
I'm happy to do that.

**Comment by RichardLitt** [comment]
Done! Would be great to add an install section and codecoverage using codecov.io, but as it is, looks good at the moment.

**Comment by RichardLitt** [comment]
Also, sorry for the delay in responding. :)
