### ISSUE TITLE
Synchronize with multicodec?

### ISSUE THREAD

**Issue by tabrath** [multiformats/multihash#65]
Just wondering if multihash is supposed to support the algorithms in the [multicodec table](https://github.com/multiformats/multicodec/blob/master/table.csv)?

**Comment by lgierth** [comment]
multicodec is for describing the format/encoding of data. It's one layer above multihash, so to speak, and you'll see that multihash is listed in the table :)

**Comment by jbenet** [comment]
yes-- the multihash table has merged into the multicodec table. afaik, the codes in the multicodec table are the right ones. the multihash table is just a subset. cc @diasdavid

**Comment by diasdavid** [comment]
Exactly what @jbenet said. @tabrath did you find any inconsistency?

**Comment by tabrath** [comment]
Well, if multihash is supposed to be just a subset of the multicodec table, there's no inconsitency. Was just wondering if multihash was supposed to support the hashing algorithms defined in the multicodec table, ie. murmur3.

As for my implementation [cs-multihash](https://github.com/multiformats/cs-multihash), I've added those in the multicodec table. But as none of the other implementations has added them, I might as well drop those, at least the actual hash calculations and verifications.

**Comment by diasdavid** [comment]
Ah, got it. Most of them will come as needed/requested. I don't think you have to drop them, unless if you are concerned with the binary size of the apps that use cs-multihash, otherwise all good :)
