### ISSUE TITLE
multicodec table and multihash table are out of sync

### ISSUE THREAD

**Issue by dignifiedquire** [multiformats/multihash#66]
https://github.com/multiformats/multicodec/blob/master/table.csv has a lot more entries, which includes relevant entries for example for the keccak family

**Comment by dignifiedquire** [comment]
cc @jbenet @diasdavid

**Comment by lgierth** [comment]
Are multihash numbers supposed to be a subset of multicodec? If so, we should remove the multihash table and point to multicodec instead. More tables = more likely they get badly out of sync.

**Comment by tabrath** [comment]
Probably relevant to #65
