### ISSUE TITLE
Java 9 & Bouncy Castle Digests <> Multihash Supported Library

### ISSUE THREAD

**Issue by jamespedwards42** [multiformats/multihash#73]
I've added [decoding support](https://github.com/comodal/hash-overlay#multihash-support) to my Java message digest library [hash-overlay](https://github.com/comodal/hash-overlay).  There are no complete encoding utilities (intentional), but there are functions for varint encoding, getters for multihash function codes, and getters for digest lengths.

You can quickly visualize all of the supported digest functions [here](https://github.com/comodal/hash-overlay/tree/master/src/systems.comodal.hash_overlay/java/systems/comodal/hash). And the intersection of multihash functions [here](https://github.com/comodal/hash-overlay/blob/master/src/systems.comodal.hash_overlay/java/systems/comodal/hash/multihash/HashFactoryFnCodeFactory.java#L15).

Opening this issue to see if there is any interest in adding this implementation to this projects readme.

**Comment by jbenet** [comment]
Very cool, yeah definitely. PR it in where you think it makes most sense.

**Comment by jamespedwards42** [comment]
Thanks! opened up a couple of PR's:

https://github.com/multiformats/multiformats/pull/38
https://github.com/multiformats/multihash/pull/75
