### ISSUE TITLE
Shouldn't type (and perhaps size) be extensible in order to future proof?

### ISSUE THREAD

**Issue by zimeon** [multiformats/multihash#81]
It seems that the current table of types https://github.com/multiformats/multihash/blob/master/hashtable.csv has started to grow quite rapidly. If the choice of `0xb2` is reversed then it would be possible to use the high-bit with a [UTF-8](https://en.wikipedia.org/wiki/UTF-8)-like scheme to extend to multiple bytes as necessary, but obviously many other extension schemes would be possible.

**Comment by Kubuxu** [comment]
It is already expandable as it is a varint. See https://github.com/multiformats/unsigned-varint

**Comment by zimeon** [comment]
Cool, my bad.
