### ISSUE TITLE
Skein hash (for fine-grained uses)

### ISSUE THREAD

**Issue by DonaldTsang** [multiformats/multihash#82]
Skein hashes can have arbitrary lengths.
Which means that the same algorithm can be used to generate 256, 512 and 1024 bit hashes.
A longer hash means files are less likely to have hash collisions.
They can also produce shorter hashes for convenience.
It is as fast as BLAKE, faster than all other SHA3 finalists and SHA2.

**Comment by DonaldTsang** [comment]
Using 3xx code for 256-XXX, 512-XXX and 1024-XXX skein hashes would be good.
http://www.skein-hash.info/sites/default/files/skein1.3.pdf
www.skein-hash.info/sites/default/files/NIST_CD_102610.zip

**Comment by DonaldTsang** [comment]
Skein Hashes | Description | Multihash code
-|-|-
Skein256-8 | | 0xc01
Skein256-16 | | 0xc02
Skein256-24 | | 0xc03
Skein256-32 | | 0xc04
Skein256-40 | | 0xc05
Skein256-48 | | 0xc06
Skein256-56 | | 0xc07
Skein256-64 | | 0xc08
Skein256-72 | | 0xc09
Skein256-80 | | 0xc0a
Skein256-88 | | 0xc0b
Skein256-96 | | 0xc0c
Skein256-104 | | 0xc0d
Skein256-112 | | 0xc0e
Skein256-120 | | 0xc0f
Skein256-128 | | 0xc10
Skein256-136 | | 0xc11
Skein256-144 | | 0xc12
Skein256-152 | | 0xc13
Skein256-160 | | 0xc14
Skein256-168 | | 0xc15
Skein256-176 | | 0xc16
Skein256-184 | | 0xc17
Skein256-192 | | 0xc18
Skein256-200 | | 0xc19
Skein256-208 | | 0xc1a
Skein256-216 | | 0xc1b
Skein256-224 | | 0xc1c
Skein256-232 | | 0xc1d
Skein256-240 | | 0xc1e
Skein256-248 | | 0xc1f
Skein256-256 | | 0xc20
Skein512-8 | | 0xc21
Skein512-16 | | 0xc22
Skein512-24 | | 0xc23
Skein512-32 | | 0xc24
Skein512-40 | | 0xc25
Skein512-48 | | 0xc26
Skein512-56 | | 0xc27
Skein512-64 | | 0xc28
Skein512-72 | | 0xc29
Skein512-80 | | 0xc2a
Skein512-88 | | 0xc2b
Skein512-96 | | 0xc2c
Skein512-104 | | 0xc2d
Skein512-112 | | 0xc2e
Skein512-120 | | 0xc2f
Skein512-128 | | 0xc30
Skein512-136 | | 0xc31
Skein512-144 | | 0xc32
Skein512-152 | | 0xc33
Skein512-160 | | 0xc34
Skein512-168 | | 0xc35
Skein512-176 | | 0xc36
Skein512-184 | | 0xc37
Skein512-192 | | 0xc38
Skein512-200 | | 0xc39
Skein512-208 | | 0xc3a
Skein512-216 | | 0xc3b
Skein512-224 | | 0xc3c
Skein512-232 | | 0xc3d
Skein512-240 | | 0xc3e
Skein512-248 | | 0xc3f
Skein512-256 | | 0xc40
Skein512-264 | | 0xc41
Skein512-272 | | 0xc42
Skein512-280 | | 0xc43
Skein512-288 | | 0xc44
Skein512-296 | | 0xc45
Skein512-304 | | 0xc46
Skein512-312 | | 0xc47
Skein512-320 | | 0xc48
Skein512-328 | | 0xc49
Skein512-336 | | 0xc4a
Skein512-344 | | 0xc4b
Skein512-352 | | 0xc4c
Skein512-360 | | 0xc4d
Skein512-368 | | 0xc4e
Skein512-376 | | 0xc4f
Skein512-384 | | 0xc50
Skein512-392 | | 0xc51
Skein512-400 | | 0xc52
Skein512-408 | | 0xc53
Skein512-416 | | 0xc54
Skein512-424 | | 0xc55
Skein512-432 | | 0xc56
Skein512-440 | | 0xc57
Skein512-448 | | 0xc58
Skein512-456 | | 0xc59
Skein512-464 | | 0xc5a
Skein512-472 | | 0xc5b
Skein512-480 | | 0xc5c
Skein512-488 | | 0xc5d
Skein512-496 | | 0xc5e
Skein512-504 | | 0xc5f
Skein512-512 | | 0xc60
Skein1024-8 | | 0xc61
Skein1024-16 | | 0xc62
Skein1024-24 | | 0xc63
Skein1024-32 | | 0xc64
Skein1024-40 | | 0xc65
Skein1024-48 | | 0xc66
Skein1024-56 | | 0xc67
Skein1024-64 | | 0xc68
Skein1024-72 | | 0xc69
Skein1024-80 | | 0xc6a
Skein1024-88 | | 0xc6b
Skein1024-96 | | 0xc6c
Skein1024-104 | | 0xc6d
Skein1024-112 | | 0xc6e
Skein1024-120 | | 0xc6f
Skein1024-128 | | 0xc70
Skein1024-136 | | 0xc71
Skein1024-144 | | 0xc72
Skein1024-152 | | 0xc73
Skein1024-160 | | 0xc74
Skein1024-168 | | 0xc75
Skein1024-176 | | 0xc76
Skein1024-184 | | 0xc77
Skein1024-192 | | 0xc78
Skein1024-200 | | 0xc79
Skein1024-208 | | 0xc7a
Skein1024-216 | | 0xc7b
Skein1024-224 | | 0xc7c
Skein1024-232 | | 0xc7d
Skein1024-240 | | 0xc7e
Skein1024-248 | | 0xc7f
Skein1024-256 | | 0xc80
Skein1024-264 | | 0xc81
Skein1024-272 | | 0xc82
Skein1024-280 | | 0xc83
Skein1024-288 | | 0xc84
Skein1024-296 | | 0xc85
Skein1024-304 | | 0xc86
Skein1024-312 | | 0xc87
Skein1024-320 | | 0xc88
Skein1024-328 | | 0xc89
Skein1024-336 | | 0xc8a
Skein1024-344 | | 0xc8b
Skein1024-352 | | 0xc8c
Skein1024-360 | | 0xc8d
Skein1024-368 | | 0xc8e
Skein1024-376 | | 0xc8f
Skein1024-384 | | 0xc90
Skein1024-392 | | 0xc91
Skein1024-400 | | 0xc92
Skein1024-408 | | 0xc93
Skein1024-416 | | 0xc94
Skein1024-424 | | 0xc95
Skein1024-432 | | 0xc96
Skein1024-440 | | 0xc97
Skein1024-448 | | 0xc98
Skein1024-456 | | 0xc99
Skein1024-464 | | 0xc9a
Skein1024-472 | | 0xc9b
Skein1024-480 | | 0xc9c
Skein1024-488 | | 0xc9d
Skein1024-496 | | 0xc9e
Skein1024-504 | | 0xc9f
Skein1024-512 | | 0xca0
Skein1024-520 | | 0xca1
Skein1024-528 | | 0xca2
Skein1024-536 | | 0xca3
Skein1024-544 | | 0xca4
Skein1024-552 | | 0xca5
Skein1024-560 | | 0xca6
Skein1024-568 | | 0xca7
Skein1024-576 | | 0xca8
Skein1024-584 | | 0xca9
Skein1024-592 | | 0xcaa
Skein1024-600 | | 0xcab
Skein1024-608 | | 0xcac
Skein1024-616 | | 0xcad
Skein1024-624 | | 0xcae
Skein1024-632 | | 0xcaf
Skein1024-640 | | 0xcb0
Skein1024-648 | | 0xcb1
Skein1024-656 | | 0xcb2
Skein1024-664 | | 0xcb3
Skein1024-672 | | 0xcb4
Skein1024-680 | | 0xcb5
Skein1024-688 | | 0xcb6
Skein1024-696 | | 0xcb7
Skein1024-704 | | 0xcb8
Skein1024-712 | | 0xcb9
Skein1024-720 | | 0xcba
Skein1024-728 | | 0xcbb
Skein1024-736 | | 0xcbc
Skein1024-744 | | 0xcbd
Skein1024-752 | | 0xcbe
Skein1024-760 | | 0xcbf
Skein1024-768 | | 0xcc0
Skein1024-776 | | 0xcc1
Skein1024-784 | | 0xcc2
Skein1024-792 | | 0xcc3
Skein1024-800 | | 0xcc4
Skein1024-808 | | 0xcc5
Skein1024-816 | | 0xcc6
Skein1024-824 | | 0xcc7
Skein1024-832 | | 0xcc8
Skein1024-840 | | 0xcc9
Skein1024-848 | | 0xcca
Skein1024-856 | | 0xccb
Skein1024-864 | | 0xccc
Skein1024-872 | | 0xccd
Skein1024-880 | | 0xcce
Skein1024-888 | | 0xccf
Skein1024-896 | | 0xcd0
Skein1024-904 | | 0xcd1
Skein1024-912 | | 0xcd2
Skein1024-920 | | 0xcd3
Skein1024-928 | | 0xcd4
Skein1024-936 | | 0xcd5
Skein1024-944 | | 0xcd6
Skein1024-952 | | 0xcd7
Skein1024-960 | | 0xcd8
Skein1024-968 | | 0xcd9
Skein1024-976 | | 0xcda
Skein1024-984 | | 0xcdb
Skein1024-992 | | 0xcdc
Skein1024-1000 | | 0xcdd
Skein1024-1008 | | 0xcde
Skein1024-1016 | | 0xcdf
Skein1024-1024 | | 0xce0

**Comment by Kubuxu** [comment]
Please use 3byte varint range in case of hashes that take so many values. 3byte range starts at 0x4000 inclusive.

**Comment by DonaldTsang** [comment]
1024 is smaller than 2^15, so 0xc for code (next to BLAKE2), 1 byte for which Skein hash it is.

**Comment by Kubuxu** [comment]
> 1024 is smaller than 2^15, so 0xc for code (next to BLAKE2), 1 byte for which Skein hash it is.

Sorry, could you rephrase it? Blake is at `0xb2 XX`

**Comment by DonaldTsang** [comment]
Sorry, I meant 0xb3 for Skein. Edited the table and code.
Laying out Skein256 before Skein512 and Skein1024 is okay, right?

**Comment by DonaldTsang** [comment]
The BLAKE hash's code in [HERE](https://github.com/multiformats/multihash/blob/master/hashtable.csv) does not match up with the implementation in [HERE](https://github.com/multiformats/go-multihash/blob/master/sum_test.go#L34)

**Comment by DonaldTsang** [comment]
Recheck this please

**Comment by Stebalien** [comment]
Thanks for the ping.

---

The blake2b codes are now correct. The table has been moved here: https://github.com/multiformats/multicodec/blob/master/table.csv

Minimum: https://github.com/multiformats/multicodec/blob/02d384f8c569add2ac7a3b34a15d59d789520d14/table.csv#L62

Minimum: https://github.com/multiformats/go-multihash/blob/a91e75d03bf4dba801af7b159c8b2aa7b5f47ea8/multihash.go#L56

---

Skein has been added in https://github.com/multiformats/multicodec/pull/56.
