### ISSUE TITLE
Why isn't encoding included in the prefix?

### ISSUE THREAD

**Issue by nileshtrivedi** [multiformats/multihash#88]
This may be a n00b question but shouldn't we include the encoding (hex, Base32, Base58, Base64 etc) too in the prefix to make it fully self-describing? The same hash often needs to be communicated in different encodings because of various constraints (URL safety, storage limits, easier typing by humans, disambiguity while communicating over phone).

Why was encoding format left out? Will this be covered by variants?

**Comment by Stebalien** [comment]
No, that's a great question. We have a separate spec for that: https://github.com/multiformats/multibase/
