### ISSUE TITLE
Keccak 256 algorithm issue

### ISSUE THREAD

**Issue by kiranbasvaraj** [multiformats/multihash#90]
hi ,
I am using keccak-256 algorithm for generating multi-hash for string "Hello world". It supposed give output as ed6c11b0b5b808960df26f5bfc471d04c1995b0ffd2055925ad1be28d6baadfd ,but it is giving 
   1b20ed6c11b0b5b808960df26f5bfc471d04c1995b0ffd2055925ad1be28d6baadfd.

1b20 value is prefixed with the expected has-code. i want to know is this intentional and if it so,i want to know where exactly the concatenation is happening.

**Comment by Stebalien** [comment]
Yes, that's actually the point of multihash. It annotates the hash with additional information describing the hash function used. `1b` indicates that this is a "Keccak" hash and the `20` is the length (0x20 = 32bytes = 256 bits).
