### ISSUE TITLE
Xamarin.Forms compatibility

### ISSUE THREAD

**Issue by kiranbasvaraj** [multiformats/multihash#91]
Say I need to use the cs-multihash nuget on a Xamarin.Forms mobile app to create a KECCACK-256 hash on a byte array. How is this supported? Thanks in Advance.

**Comment by tabrath** [comment]
Hi, that should not be a problem if you’re using a relatively recent version of Xamarin.Forms that supports .NET Standard 1.6. Read [here](https://blog.xamarin.com/building-xamarin-forms-apps-net-standard) for assistance.

**Comment by kiranbasvaraj** [comment]
Hi ,

I managed to use the plugin by making use of .Net standard library .

Regards,
Kiran
