### ISSUE TITLE
tehmaze/python-multihash does not exist

### ISSUE THREAD

**Issue by NiKiZe** [multiformats/multihash#96]
https://github.com/tehmaze/python-multihash is linked from the readme, maybe it is temporary,
if not then a quick search gave https://github.com/JulienPalard/multihash - I don't know anything about it tho

**Comment by Stebalien** [comment]
Hm. I have no idea what happened to that. @tehmaze?

**Comment by DonaldTsang** [comment]
- https://github.com/ivilata/pymultihash
- https://github.com/JulienPalard/multihash
- https://github.com/BrendanBenshoof/py-multihash
Any good replacement?

**Comment by Stebalien** [comment]
A python multihash implementation was just moved to multiformats: https://github.com/multiformats/py-multihash
